In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv('netflix_titles.csv')

# View basic info
df.info()  # Check column names and data types
df.head()  # Preview the first few rows

In [17]:
print(df.isnull().sum())  # Count of missing values per column

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [26]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Not Available')
df['rating'] = df['rating'].fillna('Not Rated')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,documentaries,"As her father nears the end of his life, filmm..."
1,s2,tv show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"international tv shows, tv dramas, tv mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,tv show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Not Available,2021-09-24,2021,TV-MA,1 Season,"crime tv shows, international tv shows, tv act...",To protect his family from a powerful drug lor...
3,s4,tv show,Jailbirds New Orleans,Unknown,Unknown,Not Available,2021-09-24,2021,TV-MA,1 Season,"docuseries, reality tv","Feuds, flirtations and toilet talk go down amo..."
4,s5,tv show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"international tv shows, romantic tv shows, tv ...",In a city of coaching centers known to train I...

In [27]:
df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])  # Fill with most common date
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,documentaries,"As her father nears the end of his life, filmm..."
1,s2,tv show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"international tv shows, tv dramas, tv mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,tv show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Not Available,2021-09-24,2021,TV-MA,1 Season,"crime tv shows, international tv shows, tv act...",To protect his family from a powerful drug lor...
3,s4,tv show,Jailbirds New Orleans,Unknown,Unknown,Not Available,2021-09-24,2021,TV-MA,1 Season,"docuseries, reality tv","Feuds, flirtations and toilet talk go down amo..."
4,s5,tv show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"international tv shows, romantic tv shows, tv ...",In a city of coaching centers known to train I...

In [29]:
df = df.drop_duplicates()

In [24]:
df.columns = df.columns.str.lower().str.replace(' ', '_')  # Clean column names
df['type'] = df['type'].str.lower().str.strip()
df['listed_in'] = df['listed_in'].str.lower().str.strip()
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,documentaries,"As her father nears the end of his life, filmm..."
1,s2,tv show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"international tv shows, tv dramas, tv mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,tv show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Not Available,2021-09-24,2021,TV-MA,1 Season,"crime tv shows, international tv shows, tv act...",To protect his family from a powerful drug lor...
3,s4,tv show,Jailbirds New Orleans,Unknown,Unknown,Not Available,2021-09-24,2021,TV-MA,1 Season,"docuseries, reality tv","Feuds, flirtations and toilet talk go down amo..."
4,s5,tv show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"international tv shows, romantic tv shows, tv ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"cult movies, dramas, thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,tv show,Zombie Dumb,Unknown,Unknown,Not Available,2019-07-01,2018,TV-Y7,2 Seasons,"kids' tv, korean tv shows, tv comedies","While living alone in a spooky town, a young g..."
8804,s8805,movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"comedies, horror movies",Looking to survive in a world taken over by zo...
8805,s8806,movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero..."
8806,s8807,movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"dramas, international movies, music & musicals",A scrappy but poor boy worms his way into a ty...

In [31]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [32]:
print(df['date_added'].unique())  # See how dates are formatted

<DatetimeArray>
['2021-09-25 00:00:00', '2021-09-24 00:00:00', '2021-09-23 00:00:00',
 '2021-09-22 00:00:00', '2021-09-21 00:00:00', '2021-09-20 00:00:00',
 '2021-09-19 00:00:00', '2021-09-17 00:00:00', '2021-09-16 00:00:00',
 '2021-09-15 00:00:00',
 ...
 '2018-09-27 00:00:00', '2017-03-23 00:00:00', '2016-12-25 00:00:00',
 '2016-11-30 00:00:00', '2017-10-23 00:00:00', '2017-11-04 00:00:00',
 '2015-08-05 00:00:00', '2018-12-06 00:00:00', '2016-03-09 00:00:00',
 '2020-01-11 00:00:00']
Length: 1699, dtype: datetime64[ns]

In [33]:
df['date_added'] = pd.to_datetime(df['date_added'], format='%B %d, %Y', errors='coerce')

In [34]:
print(df['date_added'].isnull().sum())  # Check for NaT (missing values)

0

In [36]:
df = df.sort_values(by='date_added', ascending=True)

In [40]:
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month
df['day_added'] = df['date_added'].dt.day
df['date_added']

5957   2008-01-01
6611   2008-02-04
5956   2009-05-05
5955   2009-11-18
7370   2010-11-01
          ...
6      2021-09-24
7      2021-09-24
8      2021-09-24
9      2021-09-24
0      2021-09-25
Name: date_added, Length: 8807, dtype: datetime64[ns]

In [41]:
df['release_year'] = df['release_year'].astype(int)

In [54]:
print(df['duration'].dtype)  # Show data type of duration

float64

In [50]:
df['duration'] = df['duration'].str.extract(r'(\d+)')  # Extract numbers
df['duration'] = pd.to_numeric(df['duration'])  # Convert to integer

In [51]:
df['duration'] = df['duration'].astype(str).replace('nan', '')  # Convert NaN to empty strings
df['duration'] = df['duration'].str.extract(r'(\d+)')  # Extract numbers
df['duration'] = pd.to_numeric(df['duration'], errors='coerce')  # Convert to numeric

In [52]:
print(df.dtypes)  # Check if 'duration' is now an integer

show_id                 object
type                    object
title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year             int32
rating                  object
duration               float64
listed_in               object
description             object
year_added               int32
month_added              int32
day_added                int32
dtype: object

In [56]:
df.loc[:, 'duration'] = df['duration'].fillna(df['duration'].median())

In [57]:
df['duration'] = df['duration'].fillna(df['duration'].median())

In [67]:
print(df.info())  # Check column types and missing values
print(df.head())  # View first few rows

<class 'pandas.core.frame.DataFrame'>
Index: 8807 entries, 5957 to 0
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      8807 non-null   object
 4   cast          8807 non-null   object
 5   country       8807 non-null   object
 6   date_added    8807 non-null   datetime64[ns]
 7   release_year  8807 non-null   int32
 8   rating        8807 non-null   object
 9   duration      8807 non-null   float64
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), float64(1), int32(1), object(9)
memory usage: 860.1+ KB
None
     show_id     type                        title              director  \
5957   s5958    movie         To and From New York  Sorin Dan Mihalcescu
6611   s6612  tv show              Dinner for Five               Unknown
5956   s5957    movie      Just Another Love Story          Ole Bornedal
5955   s5956    movie                     Splatter             Joe Dante
7370   s7371    movie  Mad Ron's Prevues from Hell            Jim Monaco

                                                   cast        country  \
5957  Barbara King, Shaana Diya, John Krisiukenas, Y...  United States
6611                                            Unknown  United States
5956  Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...        Denmark
5955  Corey Feldman, Tony Todd, Tara Leigh, Erin Way...  United States
7370  Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...  United States

     date_added  release_year rating  duration  \
5957 2008-01-01          2006  TV-MA      81.0
6611 2008-02-04          2007  TV-MA       1.0
5956 2009-05-05          2007  TV-MA     104.0
5955 2009-11-18          2009  TV-MA      29.0
7370 2010-11-01          1987     NR      84.0

                                  listed_in  \
5957  dramas, independent movies, thrillers
6611           stand-up comedy & talk shows
5956           dramas, international movies
5955                          horror movies
7370             cult movies, horror movies

                                            description
5957  While covering a story in New York City, a Sea...
6611  In each episode, four celebrities join host Jo...
5956  When he causes a car accident that leaves a yo...
5955  After committing suicide, a washed-up rocker r...
7370  This collection cherry-picks trailers, forgott...

In [68]:
column_order = ['show_id', 'type', 'title', 'director', 'cast', 'country',
                'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

df = df[column_order]  # Arrange columns in correct order

In [70]:
df.to_csv('cleaned_netflix_titles.csv', index=False)

In [71]:
df.to_excel('cleaned_netflix_titles.xlsx', index=False, sheet_name='Cleaned Data')